<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Customerdeposit
 *
 * @property int $id
 * @property string $deposit_number
 * @property int|null $payment_id
 * @property int|null $customer_id
 * @property float $amount
 * @property int|null $created_by
 * @property int|null $last_updated_by
 * @property int|null $paymentmethoditem_id
 * @property Carbon $deposit_date
 * @property Carbon $deposit_time
 * @property string|null $description
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 *
 * @property User|null $user
 * @property Customer|null $customer
 * @property Payment|null $payment
 * @property Paymentmethoditem|null $paymentmethoditem
 *
 * @package App\Models
 */
class Customerdeposit extends Model
{
	protected $table = 'customerdeposits';

	protected $casts = [
		'payment_id' => 'int',
		'customer_id' => 'int',
		'amount' => 'float',
		'created_by' => 'int',
		'last_updated_by' => 'int',
		'paymentmethoditem_id' => 'int'
	];

	protected $dates = [
		'deposit_date',
		'deposit_time'
	];

	protected $fillable = [
		'deposit_number',
		'payment_id',
		'customer_id',
		'amount',
		'created_by',
		'last_updated_by',
		'paymentmethoditem_id',
		'deposit_date',
		'deposit_time',
		'description'
	];

    protected $appends = ['sub_total', 'discount_amount', 'invoice_date', 'total_amount_paid', 'invoice_number'];

    protected $with = ['customer'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($deposit){
            $deposit->customer->updateDepositBalance();
        });

        self::deleted(function($deposit){
            $deposit->customer->updateDepositBalance();
        });

    }


    public function getSubTotalAttribute()
    {
        return $this->amount;
    }

    public function getInvoiceDateAttribute()
    {
        return $this->payment_date;
    }

    public function getTotalAmountPaidAttribute()
    {
        return $this->amount;
    }

    public function getInvoiceNumberAttribute()
    {
        return $this->deposit_number;
    }

    public function getDiscountAmountAttribute() : int
    {
        return 0;
    }

	public function user()
	{
		return $this->belongsTo(User::class, 'last_updated_by');
	}

	public function customer()
	{
		return $this->belongsTo(Customer::class);
	}

	public function payment()
	{
		return $this->belongsTo(Payment::class);
	}

	public function paymentmethoditem()
	{
		return $this->belongsTo(Paymentmethoditem::class);
	}
}
