<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class ProductionYieldHistory
 * 
 * @property int $id
 * @property int $yield
 * @property int $production_id
 * @property int $user_id
 * @property Carbon $date_added
 * @property Carbon $time_added
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * 
 * @property Production $production
 * @property User $user
 *
 * @package App\Models
 */
class ProductionYieldHistory extends Model
{
	protected $table = 'production_yield_histories';

	protected $casts = [
		'yield' => 'int',
		'production_id' => 'int',
		'user_id' => 'int'
	];

	protected $dates = [
		'date_added',
		'time_added'
	];

	protected $fillable = [
		'yield',
		'production_id',
		'user_id',
		'date_added',
		'time_added'
	];

	public function production()
	{
		return $this->belongsTo(Production::class);
	}

	public function user()
	{
		return $this->belongsTo(User::class);
	}


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function(ProductionYieldHistory $model){
            $model->production->yield_quantity = $model->production->production_yield_histories()->sum('yield');
            $model->production->update();
        });

        self::deleted(function(ProductionYieldHistory $model){
            $model->production->yield_quantity = $model->production->production_yield_histories()->sum('yield');
            $model->production->update();
        });
    }

}
